In [1]:
file = "001_fit"

In [2]:
import polars as pl

df = pl.read_parquet("dataset.parquet")

In [3]:
df

shape: (104, 91)
┌──────────┬──────────┬────────────┬────────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ backbone ┆ pyridone ┆ backbone_h ┆ backbone_l ┆ … ┆ pyridone_ ┆ alpha_av ┆ beta_av   ┆ beta_alph │
│ ---      ┆ ---      ┆ omo        ┆ umo        ┆   ┆ L_label3  ┆ ---      ┆ ---       ┆ a         │
│ i64      ┆ i64      ┆ ---        ┆ ---        ┆   ┆ ---       ┆ f64      ┆ f64       ┆ ---       │
│          ┆          ┆ f64        ┆ f64        ┆   ┆ f64       ┆          ┆           ┆ f64       │
╞══════════╪══════════╪════════════╪════════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 0        ┆ 0        ┆ -0.388311  ┆ -0.319427  ┆ … ┆ 4.6939    ┆ 4.114632 ┆ 51.388357 ┆ 2.524862  │
│ 1        ┆ 0        ┆ -0.384586  ┆ -0.317421  ┆ … ┆ 4.6939    ┆ 3.998281 ┆ 51.539999 ┆ 2.556494  │
│ 2        ┆ 0        ┆ -0.381723  ┆ -0.314163  ┆ … ┆ 4.6939    ┆ 3.428027 ┆ 47.832328 ┆ 2.635717  │
│ 3        ┆ 0        ┆ -0.381061  ┆ -0.315206  ┆ … ┆ 4.6939    ┆ 3.636433 ┆ 47.845209 ┆ 2.576968  │
│ 4        ┆ 0        ┆ -0.380868  ┆ -0.315417  ┆ … ┆ 4.6939    ┆ 3.323485 ┆ 43.960253 ┆ 2.582272  │
│ …        ┆ …        ┆ …          ┆ …          ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ 3        ┆ 12       ┆ -0.381061  ┆ -0.315206  ┆ … ┆ 6.792953  ┆ 3.583822 ┆ 46.114252 ┆ 2.554692  │
│ 4        ┆ 12       ┆ -0.380868  ┆ -0.315417  ┆ … ┆ 6.792953  ┆ 3.742613 ┆ 49.74711  ┆ 2.587168  │
│ 5        ┆ 12       ┆ -0.385259  ┆ -0.318421  ┆ … ┆ 6.792953  ┆ 1.175172 ┆ 48.959898 ┆ 3.729587  │
│ 19       ┆ 12       ┆ -0.377896  ┆ -0.312465  ┆ … ┆ 6.792953  ┆ 3.338815 ┆ 41.066778 ┆ 2.509583  │
│ 20       ┆ 12       ┆ -0.38298   ┆ -0.317786  ┆ … ┆ 6.792953  ┆ 2.762772 ┆ 23.601443 ┆ 2.145073  │
└──────────┴──────────┴────────────┴────────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [4]:
column_group = "pyridone"
column_fix = "backbone"
columns_feat = [col for col in df.columns if col.startswith(("pyridone_", "backbone_"))]
column_target = "beta_alpha"

In [5]:
import numpy as np
from sklearn.linear_model import Ridge
from sklearn.metrics import root_mean_squared_error
from sklearn.preprocessing import StandardScaler

df_train_val_preds = []
df_test_preds = []
df_coefs = []

"""
Outer cross-validation
"""
groups_test = df[column_group].unique(maintain_order=True)

for group_test in groups_test:
    print(f"group_test: {group_test}")
    
    df_train_val = df.filter(pl.col(column_group) != group_test)
    df_test = df.filter(pl.col(column_group) == group_test)
    
    """
    Recursive feature elimination (RFE)
    """
    columns_rfe = columns_feat.copy()
    
    while len(columns_rfe) > 4:
        n_features = len(columns_rfe)
        print(f"n_features: {n_features}")
        
        X_train_val = df_train_val.select(columns_rfe).to_numpy()
        y_train_val = df_train_val.select(column_target).to_numpy()
        X_test = df_test.select(columns_rfe).to_numpy()
        y_test = df_test.select(column_target).to_numpy()
        
        ss_X = StandardScaler()
        ss_y = StandardScaler()
        
        X_train_val_ = ss_X.fit_transform(X_train_val)
        y_train_val_ = ss_y.fit_transform(y_train_val)
        X_test_ = ss_X.transform(X_test)
        y_test_ = ss_y.transform(y_test)
        
        """
        Hyperparameter optimization
        """
        alpha = 100
        
        for i in range(1, -3, -1):
            rmses = {}
            
            for j in range(-9, 10):
                y_val_preds_ = []
                y_val_trues_ = []
                
                """
                Inner cross-validation
                """
                groups_val = df_train_val[column_group].unique(maintain_order=True)
                
                for group_val in groups_val:
                    df_train = df_train_val.filter(pl.col(column_group) != group_val)
                    df_val = df_train_val.filter(pl.col(column_group) == group_val)
                    
                    X_train = df_train.select(columns_rfe).to_numpy()
                    y_train = df_train.select(column_target).to_numpy()
                    X_val = df_val.select(columns_rfe).to_numpy()
                    y_val = df_val.select(column_target).to_numpy()
                    
                    X_train_ = ss_X.transform(X_train)
                    y_train_ = ss_y.transform(y_train)
                    X_val_ = ss_X.transform(X_val)
                    y_val_ = ss_y.transform(y_val)
                    
                    model = Ridge(alpha + j * 10**i)
                    model.fit(X_train_, y_train_)
                    
                    y_val_pred_ = model.predict(X_val_)
                    y_val_preds_.append(y_val_pred_)
                    y_val_trues_.append(y_val_)
                
                y_val_preds_ = np.concatenate(y_val_preds_)
                y_val_trues_ = np.concatenate(y_val_trues_)
                rmses[j] = root_mean_squared_error(y_val_trues_, y_val_preds_)
            
            j_min = min(rmses, key=rmses.get)
            alpha += j_min * 10**i
        
        """
        Refit with the best hyperparameter
        """
        model = Ridge(alpha)
        model.fit(X_train_val_, y_train_val_)
        
        """
        Store data
        """
        y_train_val_pred_ = model.predict(X_train_val_)
        y_train_val_pred = ss_y.inverse_transform(y_train_val_pred_)
        df_train_val_pred = pl.DataFrame(
            {
                f"{column_group}_test": group_test,
                "n_features": n_features,
                column_group: df_train_val[column_group],
                column_fix: df_train_val[column_fix],
                column_target: df_train_val[column_target],
                f"{column_target}_pred": y_train_val_pred.ravel()
            }
        )
        df_train_val_preds.append(df_train_val_pred)
        
        y_test_pred_ = model.predict(X_test_)
        y_test_pred = ss_y.inverse_transform(y_test_pred_)
        df_test_pred = pl.DataFrame(
            {
                f"{column_group}_test": group_test,
                "n_features": n_features,
                column_fix: df_test[column_fix],
                column_target: df_test[column_target],
                f"{column_target}_pred": y_test_pred.ravel()
            }
        )
        df_test_preds.append(df_test_pred)
        
        coef = model.coef_
        df_coef = (
            pl.DataFrame(coef, schema=columns_rfe)
            .with_columns(
                pl.lit(group_test).alias(f"{column_group}_test"),
                pl.lit(n_features).alias("n_features"),
                pl.lit(alpha).alias("alpha"),
            )
            .select([f"{column_group}_test", "n_features", "alpha"] + columns_rfe)
        )
        df_coefs.append(df_coef)
        
        """
        Feature elimination
        """
        column_eliminate = columns_rfe[np.argmin(np.abs(coef))]
        columns_rfe = [column for column in columns_rfe if column != column_eliminate]

group_test: 0
n_features: 86
n_features: 85
n_features: 84
n_features: 83
n_features: 82
n_features: 81
n_features: 80
n_features: 79
n_features: 78
n_features: 77
n_features: 76
n_features: 75
n_features: 74
n_features: 73
n_features: 72
n_features: 71
n_features: 70
n_features: 69
n_features: 68
n_features: 67
n_features: 66
n_features: 65
n_features: 64
n_features: 63
n_features: 62
n_features: 61
n_features: 60
n_features: 59
n_features: 58
n_features: 57
n_features: 56
n_features: 55
n_features: 54
n_features: 53
n_features: 52
n_features: 51
n_features: 50
n_features: 49
n_features: 48
n_features: 47
n_features: 46
n_features: 45
n_features: 44
n_features: 43
n_features: 42
n_features: 41
n_features: 40
n_features: 39
n_features: 38
n_features: 37
n_features: 36
n_features: 35
n_features: 34
n_features: 33
n_features: 32
n_features: 31
n_features: 30
n_features: 29
n_features: 28
n_features: 27
n_features: 26
n_features: 25
n_features: 24
n_features: 23
n_features: 22
n_features: 21
n_features: 20
n_features: 19
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 1
n_features: 86
n_features: 85
n_features: 84
n_features: 83
n_features: 82
n_features: 81
n_features: 80
n_features: 79
n_features: 78
n_features: 77
n_features: 76
n_features: 75
n_features: 74
n_features: 73
n_features: 72
n_features: 71
n_features: 70
n_features: 69
n_features: 68
n_features: 67
n_features: 66
n_features: 65
n_features: 64
n_features: 63
n_features: 62
n_features: 61
n_features: 60
n_features: 59
n_features: 58
n_features: 57
n_features: 56
n_features: 55
n_features: 54
n_features: 53
n_features: 52
n_features: 51
n_features: 50
n_features: 49
n_features: 48
n_features: 47
n_features: 46
n_features: 45
n_features: 44
n_features: 43
n_features: 42
n_features: 41
n_features: 40
n_features: 39
n_features: 38
n_features: 37
n_features: 36
n_features: 35
n_features: 34
n_features: 33
n_features: 32
n_features: 31
n_features: 30
n_features: 29
n_features: 28
n_features: 27
n_features: 26
n_features: 25
n_features: 24
n_features: 23
n_features: 22
n_features: 21
n_features: 20
n_features: 19
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 2
n_features: 86
n_features: 85
n_features: 84
n_features: 83
n_features: 82
n_features: 81
n_features: 80
n_features: 79
n_features: 78
n_features: 77
n_features: 76
n_features: 75
n_features: 74
n_features: 73
n_features: 72
n_features: 71
n_features: 70
n_features: 69
n_features: 68
n_features: 67
n_features: 66
n_features: 65
n_features: 64
n_features: 63
n_features: 62
n_features: 61
n_features: 60
n_features: 59
n_features: 58
n_features: 57
n_features: 56
n_features: 55
n_features: 54
n_features: 53
n_features: 52
n_features: 51
n_features: 50
n_features: 49
n_features: 48
n_features: 47
n_features: 46
n_features: 45
n_features: 44
n_features: 43
n_features: 42
n_features: 41
n_features: 40
n_features: 39
n_features: 38
n_features: 37
n_features: 36
n_features: 35
n_features: 34
n_features: 33
n_features: 32
n_features: 31
n_features: 30
n_features: 29
n_features: 28
n_features: 27
n_features: 26
n_features: 25
n_features: 24
n_features: 23
n_features: 22
n_features: 21
n_features: 20
n_features: 19
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 3
n_features: 86
n_features: 85
n_features: 84
n_features: 83
n_features: 82
n_features: 81
n_features: 80
n_features: 79
n_features: 78
n_features: 77
n_features: 76
n_features: 75
n_features: 74
n_features: 73
n_features: 72
n_features: 71
n_features: 70
n_features: 69
n_features: 68
n_features: 67
n_features: 66
n_features: 65
n_features: 64
n_features: 63
n_features: 62
n_features: 61
n_features: 60
n_features: 59
n_features: 58
n_features: 57
n_features: 56
n_features: 55
n_features: 54
n_features: 53
n_features: 52
n_features: 51
n_features: 50
n_features: 49
n_features: 48
n_features: 47
n_features: 46
n_features: 45
n_features: 44
n_features: 43
n_features: 42
n_features: 41
n_features: 40
n_features: 39
n_features: 38
n_features: 37
n_features: 36
n_features: 35
n_features: 34
n_features: 33
n_features: 32
n_features: 31
n_features: 30
n_features: 29
n_features: 28
n_features: 27
n_features: 26
n_features: 25
n_features: 24
n_features: 23
n_features: 22
n_features: 21
n_features: 20
n_features: 19
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 4
n_features: 86
n_features: 85
n_features: 84
n_features: 83
n_features: 82
n_features: 81
n_features: 80
n_features: 79
n_features: 78
n_features: 77
n_features: 76
n_features: 75
n_features: 74
n_features: 73
n_features: 72
n_features: 71
n_features: 70
n_features: 69
n_features: 68
n_features: 67
n_features: 66
n_features: 65
n_features: 64
n_features: 63
n_features: 62
n_features: 61
n_features: 60
n_features: 59
n_features: 58
n_features: 57
n_features: 56
n_features: 55
n_features: 54
n_features: 53
n_features: 52
n_features: 51
n_features: 50
n_features: 49
n_features: 48
n_features: 47
n_features: 46
n_features: 45
n_features: 44
n_features: 43
n_features: 42
n_features: 41
n_features: 40
n_features: 39
n_features: 38
n_features: 37
n_features: 36
n_features: 35
n_features: 34
n_features: 33
n_features: 32
n_features: 31
n_features: 30
n_features: 29
n_features: 28
n_features: 27
n_features: 26
n_features: 25
n_features: 24
n_features: 23
n_features: 22
n_features: 21
n_features: 20
n_features: 19
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 5
n_features: 86
n_features: 85
n_features: 84
n_features: 83
n_features: 82
n_features: 81
n_features: 80
n_features: 79
n_features: 78
n_features: 77
n_features: 76
n_features: 75
n_features: 74
n_features: 73
n_features: 72
n_features: 71
n_features: 70
n_features: 69
n_features: 68
n_features: 67
n_features: 66
n_features: 65
n_features: 64
n_features: 63
n_features: 62
n_features: 61
n_features: 60
n_features: 59
n_features: 58
n_features: 57
n_features: 56
n_features: 55
n_features: 54
n_features: 53
n_features: 52
n_features: 51
n_features: 50
n_features: 49
n_features: 48
n_features: 47
n_features: 46
n_features: 45
n_features: 44
n_features: 43
n_features: 42
n_features: 41
n_features: 40
n_features: 39
n_features: 38
n_features: 37
n_features: 36
n_features: 35
n_features: 34
n_features: 33
n_features: 32
n_features: 31
n_features: 30
n_features: 29
n_features: 28
n_features: 27
n_features: 26
n_features: 25
n_features: 24
n_features: 23
n_features: 22
n_features: 21
n_features: 20
n_features: 19
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 6
n_features: 86
n_features: 85
n_features: 84
n_features: 83
n_features: 82
n_features: 81
n_features: 80
n_features: 79
n_features: 78
n_features: 77
n_features: 76
n_features: 75
n_features: 74
n_features: 73
n_features: 72
n_features: 71
n_features: 70
n_features: 69
n_features: 68
n_features: 67
n_features: 66
n_features: 65
n_features: 64
n_features: 63
n_features: 62
n_features: 61
n_features: 60
n_features: 59
n_features: 58
n_features: 57
n_features: 56
n_features: 55
n_features: 54
n_features: 53
n_features: 52
n_features: 51
n_features: 50
n_features: 49
n_features: 48
n_features: 47
n_features: 46
n_features: 45
n_features: 44
n_features: 43
n_features: 42
n_features: 41
n_features: 40
n_features: 39
n_features: 38
n_features: 37
n_features: 36
n_features: 35
n_features: 34
n_features: 33
n_features: 32
n_features: 31
n_features: 30
n_features: 29
n_features: 28
n_features: 27
n_features: 26
n_features: 25
n_features: 24
n_features: 23
n_features: 22
n_features: 21
n_features: 20
n_features: 19
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 7
n_features: 86
n_features: 85
n_features: 84
n_features: 83
n_features: 82
n_features: 81
n_features: 80
n_features: 79
n_features: 78
n_features: 77
n_features: 76
n_features: 75
n_features: 74
n_features: 73
n_features: 72
n_features: 71
n_features: 70
n_features: 69
n_features: 68
n_features: 67
n_features: 66
n_features: 65
n_features: 64
n_features: 63
n_features: 62
n_features: 61
n_features: 60
n_features: 59
n_features: 58
n_features: 57
n_features: 56
n_features: 55
n_features: 54
n_features: 53
n_features: 52
n_features: 51
n_features: 50
n_features: 49
n_features: 48
n_features: 47
n_features: 46
n_features: 45
n_features: 44
n_features: 43
n_features: 42
n_features: 41
n_features: 40
n_features: 39
n_features: 38
n_features: 37
n_features: 36
n_features: 35
n_features: 34
n_features: 33
n_features: 32
n_features: 31
n_features: 30
n_features: 29
n_features: 28
n_features: 27
n_features: 26
n_features: 25
n_features: 24
n_features: 23
n_features: 22
n_features: 21
n_features: 20
n_features: 19
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 8
n_features: 86
n_features: 85
n_features: 84
n_features: 83
n_features: 82
n_features: 81
n_features: 80
n_features: 79
n_features: 78
n_features: 77
n_features: 76
n_features: 75
n_features: 74
n_features: 73
n_features: 72
n_features: 71
n_features: 70
n_features: 69
n_features: 68
n_features: 67
n_features: 66
n_features: 65
n_features: 64
n_features: 63
n_features: 62
n_features: 61
n_features: 60
n_features: 59
n_features: 58
n_features: 57
n_features: 56
n_features: 55
n_features: 54
n_features: 53
n_features: 52
n_features: 51
n_features: 50
n_features: 49
n_features: 48
n_features: 47
n_features: 46
n_features: 45
n_features: 44
n_features: 43
n_features: 42
n_features: 41
n_features: 40
n_features: 39
n_features: 38
n_features: 37
n_features: 36
n_features: 35
n_features: 34
n_features: 33
n_features: 32
n_features: 31
n_features: 30
n_features: 29
n_features: 28
n_features: 27
n_features: 26
n_features: 25
n_features: 24
n_features: 23
n_features: 22
n_features: 21
n_features: 20
n_features: 19
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 9
n_features: 86
n_features: 85
n_features: 84
n_features: 83
n_features: 82
n_features: 81
n_features: 80
n_features: 79
n_features: 78
n_features: 77
n_features: 76
n_features: 75
n_features: 74
n_features: 73
n_features: 72
n_features: 71
n_features: 70
n_features: 69
n_features: 68
n_features: 67
n_features: 66
n_features: 65
n_features: 64
n_features: 63
n_features: 62
n_features: 61
n_features: 60
n_features: 59
n_features: 58
n_features: 57
n_features: 56
n_features: 55
n_features: 54
n_features: 53
n_features: 52
n_features: 51
n_features: 50
n_features: 49
n_features: 48
n_features: 47
n_features: 46
n_features: 45
n_features: 44
n_features: 43
n_features: 42
n_features: 41
n_features: 40
n_features: 39
n_features: 38
n_features: 37
n_features: 36
n_features: 35
n_features: 34
n_features: 33
n_features: 32
n_features: 31
n_features: 30
n_features: 29
n_features: 28
n_features: 27
n_features: 26
n_features: 25
n_features: 24
n_features: 23
n_features: 22
n_features: 21
n_features: 20
n_features: 19
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 10
n_features: 86
n_features: 85
n_features: 84
n_features: 83
n_features: 82
n_features: 81
n_features: 80
n_features: 79
n_features: 78
n_features: 77
n_features: 76
n_features: 75
n_features: 74
n_features: 73
n_features: 72
n_features: 71
n_features: 70
n_features: 69
n_features: 68
n_features: 67
n_features: 66
n_features: 65
n_features: 64
n_features: 63
n_features: 62
n_features: 61
n_features: 60
n_features: 59
n_features: 58
n_features: 57
n_features: 56
n_features: 55
n_features: 54
n_features: 53
n_features: 52
n_features: 51
n_features: 50
n_features: 49
n_features: 48
n_features: 47
n_features: 46
n_features: 45
n_features: 44
n_features: 43
n_features: 42
n_features: 41
n_features: 40
n_features: 39
n_features: 38
n_features: 37
n_features: 36
n_features: 35
n_features: 34
n_features: 33
n_features: 32
n_features: 31
n_features: 30
n_features: 29
n_features: 28
n_features: 27
n_features: 26
n_features: 25
n_features: 24
n_features: 23
n_features: 22
n_features: 21
n_features: 20
n_features: 19
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 11
n_features: 86
n_features: 85
n_features: 84
n_features: 83
n_features: 82
n_features: 81
n_features: 80
n_features: 79
n_features: 78
n_features: 77
n_features: 76
n_features: 75
n_features: 74
n_features: 73
n_features: 72
n_features: 71
n_features: 70
n_features: 69
n_features: 68
n_features: 67
n_features: 66
n_features: 65
n_features: 64
n_features: 63
n_features: 62
n_features: 61
n_features: 60
n_features: 59
n_features: 58
n_features: 57
n_features: 56
n_features: 55
n_features: 54
n_features: 53
n_features: 52
n_features: 51
n_features: 50
n_features: 49
n_features: 48
n_features: 47
n_features: 46
n_features: 45
n_features: 44
n_features: 43
n_features: 42
n_features: 41
n_features: 40
n_features: 39
n_features: 38
n_features: 37
n_features: 36
n_features: 35
n_features: 34
n_features: 33
n_features: 32
n_features: 31
n_features: 30
n_features: 29
n_features: 28
n_features: 27
n_features: 26
n_features: 25
n_features: 24
n_features: 23
n_features: 22
n_features: 21
n_features: 20
n_features: 19
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 12
n_features: 86
n_features: 85
n_features: 84
n_features: 83
n_features: 82
n_features: 81
n_features: 80
n_features: 79
n_features: 78
n_features: 77
n_features: 76
n_features: 75
n_features: 74
n_features: 73
n_features: 72
n_features: 71
n_features: 70
n_features: 69
n_features: 68
n_features: 67
n_features: 66
n_features: 65
n_features: 64
n_features: 63
n_features: 62
n_features: 61
n_features: 60
n_features: 59
n_features: 58
n_features: 57
n_features: 56
n_features: 55
n_features: 54
n_features: 53
n_features: 52
n_features: 51
n_features: 50
n_features: 49
n_features: 48
n_features: 47
n_features: 46
n_features: 45
n_features: 44
n_features: 43
n_features: 42
n_features: 41
n_features: 40
n_features: 39
n_features: 38
n_features: 37
n_features: 36
n_features: 35
n_features: 34
n_features: 33
n_features: 32
n_features: 31
n_features: 30
n_features: 29
n_features: 28
n_features: 27
n_features: 26
n_features: 25
n_features: 24
n_features: 23
n_features: 22
n_features: 21
n_features: 20
n_features: 19
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5

In [6]:
df_train_val_preds = pl.concat(df_train_val_preds, how="vertical_relaxed")
df_test_preds = pl.concat(df_test_preds, how="vertical_relaxed")
df_coefs = pl.concat(df_coefs, how="diagonal_relaxed")

In [7]:
df_train_val_preds

shape: (102_336, 6)
┌───────────────┬────────────┬──────────┬──────────┬────────────┬─────────────────┐
│ pyridone_test ┆ n_features ┆ pyridone ┆ backbone ┆ beta_alpha ┆ beta_alpha_pred │
│ ---           ┆ ---        ┆ ---      ┆ ---      ┆ ---        ┆ ---             │
│ i32           ┆ i32        ┆ i64      ┆ i64      ┆ f64        ┆ f64             │
╞═══════════════╪════════════╪══════════╪══════════╪════════════╪═════════════════╡
│ 0             ┆ 86         ┆ 1        ┆ 0        ┆ 2.928763   ┆ 3.10568         │
│ 0             ┆ 86         ┆ 1        ┆ 1        ┆ 2.982038   ┆ 3.121946        │
│ 0             ┆ 86         ┆ 1        ┆ 2        ┆ 3.21741    ┆ 3.12174         │
│ 0             ┆ 86         ┆ 1        ┆ 3        ┆ 3.161632   ┆ 3.012969        │
│ 0             ┆ 86         ┆ 1        ┆ 4        ┆ 3.217922   ┆ 3.028099        │
│ …             ┆ …          ┆ …        ┆ …        ┆ …          ┆ …               │
│ 12            ┆ 5          ┆ 11       ┆ 3        ┆ 2.003263   ┆ 2.165063        │
│ 12            ┆ 5          ┆ 11       ┆ 4        ┆ 2.016259   ┆ 2.192045        │
│ 12            ┆ 5          ┆ 11       ┆ 5        ┆ 3.974007   ┆ 3.342268        │
│ 12            ┆ 5          ┆ 11       ┆ 19       ┆ 1.676942   ┆ 2.04201         │
│ 12            ┆ 5          ┆ 11       ┆ 20       ┆ 1.704931   ┆ 1.848364        │
└───────────────┴────────────┴──────────┴──────────┴────────────┴─────────────────┘

In [8]:
df_test_preds

shape: (8_528, 5)
┌───────────────┬────────────┬──────────┬────────────┬─────────────────┐
│ pyridone_test ┆ n_features ┆ backbone ┆ beta_alpha ┆ beta_alpha_pred │
│ ---           ┆ ---        ┆ ---      ┆ ---        ┆ ---             │
│ i32           ┆ i32        ┆ i64      ┆ f64        ┆ f64             │
╞═══════════════╪════════════╪══════════╪════════════╪═════════════════╡
│ 0             ┆ 86         ┆ 0        ┆ 2.524862   ┆ 2.698814        │
│ 0             ┆ 86         ┆ 1        ┆ 2.556494   ┆ 2.71508         │
│ 0             ┆ 86         ┆ 2        ┆ 2.635717   ┆ 2.714874        │
│ 0             ┆ 86         ┆ 3        ┆ 2.576968   ┆ 2.606103        │
│ 0             ┆ 86         ┆ 4        ┆ 2.582272   ┆ 2.621233        │
│ …             ┆ …          ┆ …        ┆ …          ┆ …               │
│ 12            ┆ 5          ┆ 3        ┆ 2.554692   ┆ 2.59081         │
│ 12            ┆ 5          ┆ 4        ┆ 2.587168   ┆ 2.617793        │
│ 12            ┆ 5          ┆ 5        ┆ 3.729587   ┆ 3.768015        │
│ 12            ┆ 5          ┆ 19       ┆ 2.509583   ┆ 2.467757        │
│ 12            ┆ 5          ┆ 20       ┆ 2.145073   ┆ 2.274112        │
└───────────────┴────────────┴──────────┴────────────┴─────────────────┘

In [9]:
df_coefs

shape: (1_066, 89)
┌────────────┬────────────┬───────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ pyridone_t ┆ n_features ┆ alpha ┆ backbone_h ┆ … ┆ pyridone_ ┆ pyridone_ ┆ pyridone_ ┆ pyridone_ │
│ est        ┆ ---        ┆ ---   ┆ omo        ┆   ┆ vbur_labe ┆ B1_label3 ┆ B5_label3 ┆ L_label3  │
│ ---        ┆ i32        ┆ f64   ┆ ---        ┆   ┆ l3        ┆ ---       ┆ ---       ┆ ---       │
│ i32        ┆            ┆       ┆ f64        ┆   ┆ ---       ┆ f64       ┆ f64       ┆ f64       │
│            ┆            ┆       ┆            ┆   ┆ f64       ┆           ┆           ┆           │
╞════════════╪════════════╪═══════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0          ┆ 86         ┆ 0.01  ┆ -0.022868  ┆ … ┆ -0.055671 ┆ 0.052275  ┆ 0.015496  ┆ -0.025115 │
│ 0          ┆ 85         ┆ 0.01  ┆ -0.022868  ┆ … ┆ -0.055671 ┆ 0.052275  ┆ 0.015496  ┆ -0.025115 │
│ 0          ┆ 84         ┆ 0.01  ┆ -0.022868  ┆ … ┆ -0.055671 ┆ 0.052275  ┆ 0.015496  ┆ -0.025115 │
│ 0          ┆ 83         ┆ 0.01  ┆ -0.022868  ┆ … ┆ -0.055671 ┆ 0.052275  ┆ 0.015496  ┆ -0.025115 │
│ 0          ┆ 82         ┆ 0.01  ┆ -0.022866  ┆ … ┆ -0.055671 ┆ 0.052275  ┆ 0.015496  ┆ -0.025115 │
│ …          ┆ …          ┆ …     ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 12         ┆ 9          ┆ 18.15 ┆ null       ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 12         ┆ 8          ┆ 14.94 ┆ null       ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 12         ┆ 7          ┆ 0.55  ┆ null       ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 12         ┆ 6          ┆ 0.46  ┆ null       ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 12         ┆ 5          ┆ 0.91  ┆ null       ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
└────────────┴────────────┴───────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [10]:
df_train_val_preds.write_parquet(f"{file}_train_val_preds.parquet")
df_test_preds.write_parquet(f"{file}_test_preds.parquet")
df_coefs.write_parquet(f"{file}_coefs.parquet")