In [1]:
file = "004_fit_MPAA"

In [2]:
import polars as pl

df = pl.read_parquet("dataset_selectivity.parquet")

In [3]:
df

shape: (104, 43)
┌──────────┬──────────┬───────────┬──────────┬───┬──────────┬──────────┬──────────┬────────────┐
│ backbone ┆ pyridone ┆ 12        ┆ 21       ┆ … ┆ 602      ┆ 605      ┆ 642      ┆ beta_alpha │
│ ---      ┆ ---      ┆ ---       ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---        │
│ i64      ┆ i64      ┆ f64       ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64        │
╞══════════╪══════════╪═══════════╪══════════╪═══╪══════════╪══════════╪══════════╪════════════╡
│ 0        ┆ 0        ┆ -0.000914 ┆ 0.002204 ┆ … ┆ 0.005874 ┆ 0.008591 ┆ 0.006254 ┆ 2.524862   │
│ 1        ┆ 0        ┆ -0.0009   ┆ 0.002456 ┆ … ┆ 0.005882 ┆ 0.008736 ┆ 0.006282 ┆ 2.556494   │
│ 2        ┆ 0        ┆ -0.000929 ┆ 0.002349 ┆ … ┆ 0.005878 ┆ 0.008327 ┆ 0.00629  ┆ 2.635717   │
│ 3        ┆ 0        ┆ -0.000935 ┆ 0.002466 ┆ … ┆ 0.005884 ┆ 0.008192 ┆ 0.006119 ┆ 2.576968   │
│ 4        ┆ 0        ┆ -0.000867 ┆ 0.002484 ┆ … ┆ 0.005881 ┆ 0.008694 ┆ 0.006291 ┆ 2.582272   │
│ …        ┆ …        ┆ …         ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …          │
│ 3        ┆ 12       ┆ -0.001763 ┆ 0.002501 ┆ … ┆ 0.005882 ┆ 0.007728 ┆ 0.006251 ┆ 2.554692   │
│ 4        ┆ 12       ┆ -0.001706 ┆ 0.00252  ┆ … ┆ 0.005879 ┆ 0.007745 ┆ 0.006266 ┆ 2.587168   │
│ 5        ┆ 12       ┆ -0.001751 ┆ 0.002629 ┆ … ┆ 0.005884 ┆ 0.008312 ┆ 0.006275 ┆ 3.729587   │
│ 19       ┆ 12       ┆ -0.001744 ┆ 0.002359 ┆ … ┆ 0.005881 ┆ 0.007914 ┆ 0.00624  ┆ 2.509583   │
│ 20       ┆ 12       ┆ -0.001744 ┆ 0.002407 ┆ … ┆ 0.005882 ┆ 0.009066 ┆ 0.005902 ┆ 2.145073   │
└──────────┴──────────┴───────────┴──────────┴───┴──────────┴──────────┴──────────┴────────────┘

In [4]:
column_group = "backbone"
column_fix = "pyridone"
columns_feat = [c for c in df.columns if c.isnumeric()]
column_target = "beta_alpha"

In [5]:
import numpy as np
from sklearn.linear_model import Ridge
from sklearn.metrics import root_mean_squared_error
from sklearn.preprocessing import StandardScaler

df_train_val_preds = []
df_test_preds = []
df_coefs = []

"""
Outer cross-validation
"""
groups_test = df[column_group].unique(maintain_order=True)

for group_test in groups_test:
    print(f"group_test: {group_test}")
    
    df_train_val = df.filter(pl.col(column_group) != group_test)
    df_test = df.filter(pl.col(column_group) == group_test)
    
    """
    Recursive feature elimination (RFE)
    """
    columns_rfe = columns_feat.copy()
    
    while len(columns_rfe) > 4:
        n_features = len(columns_rfe)
        print(f"n_features: {n_features}")
        
        X_train_val = df_train_val.select(columns_rfe).to_numpy()
        y_train_val = df_train_val.select(column_target).to_numpy()
        X_test = df_test.select(columns_rfe).to_numpy()
        y_test = df_test.select(column_target).to_numpy()
        
        ss_X = StandardScaler()
        ss_y = StandardScaler()
        
        X_train_val_ = ss_X.fit_transform(X_train_val)
        y_train_val_ = ss_y.fit_transform(y_train_val)
        X_test_ = ss_X.transform(X_test)
        y_test_ = ss_y.transform(y_test)
        
        """
        Hyperparameter optimization
        """
        alpha = 100
        
        for i in range(1, -3, -1):
            rmses = {}
            
            for j in range(-9, 10):
                y_val_preds_ = []
                y_val_trues_ = []
                
                """
                Inner cross-validation
                """
                groups_val = df_train_val[column_group].unique(maintain_order=True)
                
                for group_val in groups_val:
                    df_train = df_train_val.filter(pl.col(column_group) != group_val)
                    df_val = df_train_val.filter(pl.col(column_group) == group_val)
                    
                    X_train = df_train.select(columns_rfe).to_numpy()
                    y_train = df_train.select(column_target).to_numpy()
                    X_val = df_val.select(columns_rfe).to_numpy()
                    y_val = df_val.select(column_target).to_numpy()
                    
                    X_train_ = ss_X.transform(X_train)
                    y_train_ = ss_y.transform(y_train)
                    X_val_ = ss_X.transform(X_val)
                    y_val_ = ss_y.transform(y_val)
                    
                    model = Ridge(alpha + j * 10**i)
                    model.fit(X_train_, y_train_)
                    
                    y_val_pred_ = model.predict(X_val_)
                    y_val_preds_.append(y_val_pred_)
                    y_val_trues_.append(y_val_)
                
                y_val_preds_ = np.concatenate(y_val_preds_)
                y_val_trues_ = np.concatenate(y_val_trues_)
                rmses[j] = root_mean_squared_error(y_val_trues_, y_val_preds_)
            
            j_min = min(rmses, key=rmses.get)
            alpha += j_min * 10**i
        
        """
        Refit with the best hyperparameter
        """
        model = Ridge(alpha)
        model.fit(X_train_val_, y_train_val_)
        
        """
        Store data
        """
        y_train_val_pred_ = model.predict(X_train_val_)
        y_train_val_pred = ss_y.inverse_transform(y_train_val_pred_)
        df_train_val_pred = pl.DataFrame(
            {
                f"{column_group}_test": group_test,
                "n_features": n_features,
                column_group: df_train_val[column_group],
                column_fix: df_train_val[column_fix],
                column_target: df_train_val[column_target],
                f"{column_target}_pred": y_train_val_pred.ravel()
            }
        )
        df_train_val_preds.append(df_train_val_pred)
        
        y_test_pred_ = model.predict(X_test_)
        y_test_pred = ss_y.inverse_transform(y_test_pred_)
        df_test_pred = pl.DataFrame(
            {
                f"{column_group}_test": group_test,
                "n_features": n_features,
                column_fix: df_test[column_fix],
                column_target: df_test[column_target],
                f"{column_target}_pred": y_test_pred.ravel()
            }
        )
        df_test_preds.append(df_test_pred)
        
        coef = model.coef_
        df_coef = (
            pl.DataFrame(coef, schema=columns_rfe)
            .with_columns(
                pl.lit(group_test).alias(f"{column_group}_test"),
                pl.lit(n_features).alias("n_features"),
                pl.lit(alpha).alias("alpha"),
            )
            .select([f"{column_group}_test", "n_features", "alpha"] + columns_rfe)
        )
        df_coefs.append(df_coef)
        
        """
        Feature elimination
        """
        column_eliminate = columns_rfe[np.argmin(np.abs(coef))]
        columns_rfe = [column for column in columns_rfe if column != column_eliminate]

group_test: 0
n_features: 40
n_features: 39
n_features: 38
n_features: 37
n_features: 36
n_features: 35
n_features: 34
n_features: 33
n_features: 32
n_features: 31
n_features: 30
n_features: 29
n_features: 28
n_features: 27
n_features: 26
n_features: 25
n_features: 24
n_features: 23
n_features: 22
n_features: 21
n_features: 20
n_features: 19
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 1
n_features: 40
n_features: 39
n_features: 38
n_features: 37
n_features: 36
n_features: 35
n_features: 34
n_features: 33
n_features: 32
n_features: 31
n_features: 30
n_features: 29
n_features: 28
n_features: 27
n_features: 26
n_features: 25
n_features: 24
n_features: 23
n_features: 22
n_features: 21
n_features: 20
n_features: 19
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 2
n_features: 40
n_features: 39
n_features: 38
n_features: 37
n_features: 36
n_features: 35
n_features: 34
n_features: 33
n_features: 32
n_features: 31
n_features: 30
n_features: 29
n_features: 28
n_features: 27
n_features: 26
n_features: 25
n_features: 24
n_features: 23
n_features: 22
n_features: 21
n_features: 20
n_features: 19
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 3
n_features: 40
n_features: 39
n_features: 38
n_features: 37
n_features: 36
n_features: 35
n_features: 34
n_features: 33
n_features: 32
n_features: 31
n_features: 30
n_features: 29
n_features: 28
n_features: 27
n_features: 26
n_features: 25
n_features: 24
n_features: 23
n_features: 22
n_features: 21
n_features: 20
n_features: 19
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 4
n_features: 40
n_features: 39
n_features: 38
n_features: 37
n_features: 36
n_features: 35
n_features: 34
n_features: 33
n_features: 32
n_features: 31
n_features: 30
n_features: 29
n_features: 28
n_features: 27
n_features: 26
n_features: 25
n_features: 24
n_features: 23
n_features: 22
n_features: 21
n_features: 20
n_features: 19
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 5
n_features: 40
n_features: 39
n_features: 38
n_features: 37
n_features: 36
n_features: 35
n_features: 34
n_features: 33
n_features: 32
n_features: 31
n_features: 30
n_features: 29
n_features: 28
n_features: 27
n_features: 26
n_features: 25
n_features: 24
n_features: 23
n_features: 22
n_features: 21
n_features: 20
n_features: 19
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 19
n_features: 40
n_features: 39
n_features: 38
n_features: 37
n_features: 36
n_features: 35
n_features: 34
n_features: 33
n_features: 32
n_features: 31
n_features: 30
n_features: 29
n_features: 28
n_features: 27
n_features: 26
n_features: 25
n_features: 24
n_features: 23
n_features: 22
n_features: 21
n_features: 20
n_features: 19
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 20
n_features: 40
n_features: 39
n_features: 38
n_features: 37
n_features: 36
n_features: 35
n_features: 34
n_features: 33
n_features: 32
n_features: 31
n_features: 30
n_features: 29
n_features: 28
n_features: 27
n_features: 26
n_features: 25
n_features: 24
n_features: 23
n_features: 22
n_features: 21
n_features: 20
n_features: 19
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5

In [6]:
df_train_val_preds = pl.concat(df_train_val_preds, how="vertical_relaxed")
df_test_preds = pl.concat(df_test_preds, how="vertical_relaxed")
df_coefs = pl.concat(df_coefs, how="diagonal_relaxed")

In [7]:
df_train_val_preds

shape: (26_208, 6)
┌───────────────┬────────────┬──────────┬──────────┬────────────┬─────────────────┐
│ backbone_test ┆ n_features ┆ backbone ┆ pyridone ┆ beta_alpha ┆ beta_alpha_pred │
│ ---           ┆ ---        ┆ ---      ┆ ---      ┆ ---        ┆ ---             │
│ i32           ┆ i32        ┆ i64      ┆ i64      ┆ f64        ┆ f64             │
╞═══════════════╪════════════╪══════════╪══════════╪════════════╪═════════════════╡
│ 0             ┆ 40         ┆ 1        ┆ 0        ┆ 2.556494   ┆ 2.794235        │
│ 0             ┆ 40         ┆ 2        ┆ 0        ┆ 2.635717   ┆ 2.614518        │
│ 0             ┆ 40         ┆ 3        ┆ 0        ┆ 2.576968   ┆ 2.778551        │
│ 0             ┆ 40         ┆ 4        ┆ 0        ┆ 2.582272   ┆ 2.740646        │
│ 0             ┆ 40         ┆ 5        ┆ 0        ┆ 3.727095   ┆ 2.899762        │
│ …             ┆ …          ┆ …        ┆ …        ┆ …          ┆ …               │
│ 20            ┆ 5          ┆ 2        ┆ 12       ┆ 2.69912    ┆ 2.677239        │
│ 20            ┆ 5          ┆ 3        ┆ 12       ┆ 2.554692   ┆ 2.764668        │
│ 20            ┆ 5          ┆ 4        ┆ 12       ┆ 2.587168   ┆ 2.771864        │
│ 20            ┆ 5          ┆ 5        ┆ 12       ┆ 3.729587   ┆ 2.868394        │
│ 20            ┆ 5          ┆ 19       ┆ 12       ┆ 2.509583   ┆ 2.743574        │
└───────────────┴────────────┴──────────┴──────────┴────────────┴─────────────────┘

In [8]:
df_test_preds

shape: (3_744, 5)
┌───────────────┬────────────┬──────────┬────────────┬─────────────────┐
│ backbone_test ┆ n_features ┆ pyridone ┆ beta_alpha ┆ beta_alpha_pred │
│ ---           ┆ ---        ┆ ---      ┆ ---        ┆ ---             │
│ i32           ┆ i32        ┆ i64      ┆ f64        ┆ f64             │
╞═══════════════╪════════════╪══════════╪════════════╪═════════════════╡
│ 0             ┆ 40         ┆ 0        ┆ 2.524862   ┆ 2.767489        │
│ 0             ┆ 40         ┆ 1        ┆ 2.928763   ┆ 2.956689        │
│ 0             ┆ 40         ┆ 2        ┆ 3.171724   ┆ 2.798685        │
│ 0             ┆ 40         ┆ 3        ┆ 2.984961   ┆ 2.857916        │
│ 0             ┆ 40         ┆ 4        ┆ 2.78847    ┆ 2.837399        │
│ …             ┆ …          ┆ …        ┆ …          ┆ …               │
│ 20            ┆ 5          ┆ 8        ┆ 1.808185   ┆ 2.669128        │
│ 20            ┆ 5          ┆ 9        ┆ 1.83243    ┆ 2.74072         │
│ 20            ┆ 5          ┆ 10       ┆ 1.843979   ┆ 2.853409        │
│ 20            ┆ 5          ┆ 11       ┆ 1.704931   ┆ 2.815607        │
│ 20            ┆ 5          ┆ 12       ┆ 2.145073   ┆ 2.657611        │
└───────────────┴────────────┴──────────┴────────────┴─────────────────┘

In [9]:
df_coefs

shape: (288, 43)
┌───────────────┬────────────┬────────┬──────────┬───┬──────────┬──────────┬───────────┬──────────┐
│ backbone_test ┆ n_features ┆ alpha  ┆ 12       ┆ … ┆ 597      ┆ 602      ┆ 605       ┆ 642      │
│ ---           ┆ ---        ┆ ---    ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---       ┆ ---      │
│ i32           ┆ i32        ┆ f64    ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64       ┆ f64      │
╞═══════════════╪════════════╪════════╪══════════╪═══╪══════════╪══════════╪═══════════╪══════════╡
│ 0             ┆ 40         ┆ 199.99 ┆ 0.039546 ┆ … ┆ 0.027028 ┆ 0.024657 ┆ -0.018956 ┆ 0.048467 │
│ 0             ┆ 39         ┆ 199.99 ┆ 0.039537 ┆ … ┆ 0.027026 ┆ 0.024652 ┆ -0.018949 ┆ 0.048466 │
│ 0             ┆ 38         ┆ 199.99 ┆ 0.039519 ┆ … ┆ 0.027041 ┆ 0.024665 ┆ -0.018922 ┆ 0.048444 │
│ 0             ┆ 37         ┆ 199.99 ┆ 0.03946  ┆ … ┆ 0.026904 ┆ 0.024764 ┆ -0.018975 ┆ 0.048478 │
│ 0             ┆ 36         ┆ 199.99 ┆ 0.039635 ┆ … ┆ 0.027239 ┆ 0.024518 ┆ -0.018973 ┆ 0.04853  │
│ …             ┆ …          ┆ …      ┆ …        ┆ … ┆ …        ┆ …        ┆ …         ┆ …        │
│ 20            ┆ 9          ┆ 0.01   ┆ null     ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│ 20            ┆ 8          ┆ 0.01   ┆ null     ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│ 20            ┆ 7          ┆ 0.01   ┆ null     ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│ 20            ┆ 6          ┆ 0.01   ┆ null     ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
│ 20            ┆ 5          ┆ 199.99 ┆ null     ┆ … ┆ null     ┆ null     ┆ null      ┆ null     │
└───────────────┴────────────┴────────┴──────────┴───┴──────────┴──────────┴───────────┴──────────┘

In [10]:
df_train_val_preds.write_parquet(f"{file}_train_val_preds.parquet")
df_test_preds.write_parquet(f"{file}_test_preds.parquet")
df_coefs.write_parquet(f"{file}_coefs.parquet")