In [1]:
file = "001_refit"

In [2]:
import polars as pl

df = pl.read_parquet("../../dataset.parquet")

In [3]:
df

shape: (104, 107)
┌──────────┬──────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ backbone ┆ pyridone ┆ 0          ┆ 2         ┆ … ┆ 602_zero  ┆ 605_zero  ┆ 642_zero  ┆ beta_av_l │
│ ---      ┆ ---      ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ogit      │
│ i64      ┆ i64      ┆ f64        ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---       │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ f64       │
╞══════════╪══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0        ┆ 0        ┆ -1542.9683 ┆ -1542.977 ┆ … ┆ -0.079205 ┆ -0.087926 ┆ -0.089446 ┆ 0.055549  │
│          ┆          ┆ 56         ┆ 051       ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 0        ┆ -1582.2585 ┆ -1582.267 ┆ … ┆ -0.07891  ┆ -0.085736 ┆ -0.087081 ┆ 0.061619  │
│          ┆          ┆ 95         ┆ 564       ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 0        ┆ -1700.1129 ┆ -1700.121 ┆ … ┆ -0.080326 ┆ -0.087646 ┆ -0.08901  ┆ -0.086761 │
│          ┆          ┆ 5          ┆ 83        ┆   ┆           ┆           ┆           ┆           │
│ 3        ┆ 0        ┆ -1660.8285 ┆ -1660.837 ┆ … ┆ -0.078678 ┆ -0.086442 ┆ -0.086987 ┆ -0.086245 │
│          ┆          ┆ 3          ┆ 468       ┆   ┆           ┆           ┆           ┆           │
│ 4        ┆ 0        ┆ -1700.1125 ┆ -1700.121 ┆ … ┆ -0.078223 ┆ -0.086452 ┆ -0.088093 ┆ -0.242775 │
│          ┆          ┆ 39         ┆ 489       ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …        ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 3        ┆ 12       ┆ -1775.2608 ┆ -1775.269 ┆ … ┆ -0.078144 ┆ -0.087104 ┆ -0.087674 ┆ -0.155744 │
│          ┆          ┆ 05         ┆ 743       ┆   ┆           ┆           ┆           ┆           │
│ 4        ┆ 12       ┆ -1814.5448 ┆ -1814.553 ┆ … ┆ -0.077692 ┆ -0.087091 ┆ -0.088991 ┆ -0.010116 │
│          ┆          ┆ 14         ┆ 764       ┆   ┆           ┆           ┆           ┆           │
│ 5        ┆ 12       ┆ -1927.5776 ┆ -1927.587 ┆ … ┆ -0.078492 ┆ -0.086451 ┆ -0.087795 ┆ -0.04161  │
│          ┆          ┆ 54         ┆ 112       ┆   ┆           ┆           ┆           ┆           │
│ 19       ┆ 12       ┆ -1814.5423 ┆ -1814.551 ┆ … ┆ -0.079794 ┆ -0.088365 ┆ -0.090207 ┆ -0.361206 │
│          ┆          ┆ 29         ┆ 514       ┆   ┆           ┆           ┆           ┆           │
│ 20       ┆ 12       ┆ -1888.2900 ┆ -1888.298 ┆ … ┆ -0.076616 ┆ -0.0868   ┆ -0.08797  ┆ -1.174656 │
│          ┆          ┆ 27         ┆ 794       ┆   ┆           ┆           ┆           ┆           │
└──────────┴──────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
column_group = "pyridone"
column_fix = "backbone"
columns_feat = [column for column in df.columns if "zero" in column]
column_target = "beta_av_logit"

In [5]:
import numpy as np
from sklearn.linear_model import Ridge
from sklearn.metrics import root_mean_squared_error
from sklearn.preprocessing import StandardScaler

df_preds = []
df_coefs = []

"""
Recursive feature elimination (RFE)
"""
columns_rfe = columns_feat.copy()

while len(columns_rfe) > 4:
    n_features = len(columns_rfe)
    print(f"n_features: {n_features}")
    
    X = df.select(columns_rfe).to_numpy()
    y = df.select(column_target).to_numpy()
    
    ss_X = StandardScaler()
    ss_y = StandardScaler()
    
    X_ = ss_X.fit_transform(X)
    y_ = ss_y.fit_transform(y)
    
    """
    Hyperparameter optimization
    """
    alpha = 100
    
    for i in range(1, -3, -1):
        rmses = {}
        
        for j in range(-9, 10):
            y_val_preds_ = []
            y_val_trues_ = []
            
            """
            Cross-validation
            """
            groups_val = df[column_group].unique(maintain_order=True)
            
            for group_val in groups_val:
                df_train = df.filter(pl.col(column_group) != group_val)
                df_val = df.filter(pl.col(column_group) == group_val)
                
                X_train = df_train.select(columns_rfe).to_numpy()
                y_train = df_train.select(column_target).to_numpy()
                X_val = df_val.select(columns_rfe).to_numpy()
                y_val = df_val.select(column_target).to_numpy()
                
                X_train_ = ss_X.transform(X_train)
                y_train_ = ss_y.transform(y_train)
                X_val_ = ss_X.transform(X_val)
                y_val_ = ss_y.transform(y_val)
                
                model = Ridge(alpha + j * 10**i)
                model.fit(X_train_, y_train_)
                
                y_val_pred_ = model.predict(X_val_)
                y_val_preds_.append(y_val_pred_)
                y_val_trues_.append(y_val_)
            
            y_val_preds_ = np.concatenate(y_val_preds_)
            y_val_trues_ = np.concatenate(y_val_trues_)
            rmses[j] = root_mean_squared_error(y_val_trues_, y_val_preds_)
        
        j_min = min(rmses, key=rmses.get)
        alpha += j_min * 10**i
    
    """
    Refit with the best hyperparameter
    """
    model = Ridge(alpha)
    model.fit(X_, y_)
    
    """
    Store data
    """
    y_pred_ = model.predict(X_)
    y_pred = ss_y.inverse_transform(y_pred_)
    df_pred = pl.DataFrame(
        {
            "n_features": n_features,
            column_group: df[column_group],
            column_fix: df[column_fix],
            column_target: df[column_target],
            f"{column_target}_pred": y_pred.ravel()
        }
    )
    df_preds.append(df_pred)
    
    coef = model.coef_
    df_coef = (
        pl.DataFrame(coef, schema=columns_rfe)
        .with_columns(
            pl.lit(n_features).alias("n_features"),
            pl.lit(alpha).alias("alpha"),
        )
        .select(["n_features", "alpha"] + columns_rfe)
    )
    df_coefs.append(df_coef)
    
    """
    Feature elimination
    """
    column_eliminate = columns_rfe[np.argmin(np.abs(coef))]
    columns_rfe = [column for column in columns_rfe if column != column_eliminate]

n_features: 51
n_features: 50
n_features: 49
n_features: 48
n_features: 47
n_features: 46
n_features: 45
n_features: 44
n_features: 43
n_features: 42
n_features: 41
n_features: 40
n_features: 39
n_features: 38
n_features: 37
n_features: 36
n_features: 35
n_features: 34
n_features: 33
n_features: 32
n_features: 31
n_features: 30
n_features: 29
n_features: 28
n_features: 27
n_features: 26
n_features: 25
n_features: 24
n_features: 23
n_features: 22
n_features: 21
n_features: 20
n_features: 19
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5

In [6]:
df_preds = pl.concat(df_preds, how="vertical_relaxed")
df_coefs = pl.concat(df_coefs, how="diagonal_relaxed")

In [7]:
df_preds

shape: (4_888, 5)
┌────────────┬──────────┬──────────┬───────────────┬────────────────────┐
│ n_features ┆ pyridone ┆ backbone ┆ beta_av_logit ┆ beta_av_logit_pred │
│ ---        ┆ ---      ┆ ---      ┆ ---           ┆ ---                │
│ i32        ┆ i64      ┆ i64      ┆ f64           ┆ f64                │
╞════════════╪══════════╪══════════╪═══════════════╪════════════════════╡
│ 51         ┆ 0        ┆ 0        ┆ 0.055549      ┆ 0.083511           │
│ 51         ┆ 0        ┆ 1        ┆ 0.061619      ┆ 0.029529           │
│ 51         ┆ 0        ┆ 2        ┆ -0.086761     ┆ -0.047476          │
│ 51         ┆ 0        ┆ 3        ┆ -0.086245     ┆ -0.058228          │
│ 51         ┆ 0        ┆ 4        ┆ -0.242775     ┆ -0.019353          │
│ …          ┆ …        ┆ …        ┆ …             ┆ …                  │
│ 5          ┆ 12       ┆ 3        ┆ -0.155744     ┆ -0.062729          │
│ 5          ┆ 12       ┆ 4        ┆ -0.010116     ┆ -0.092678          │
│ 5          ┆ 12       ┆ 5        ┆ -0.04161      ┆ -0.143899          │
│ 5          ┆ 12       ┆ 19       ┆ -0.361206     ┆ -0.168638          │
│ 5          ┆ 12       ┆ 20       ┆ -1.174656     ┆ -1.052164          │
└────────────┴──────────┴──────────┴───────────────┴────────────────────┘

In [8]:
df_coefs

shape: (47, 53)
┌────────────┬───────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ n_features ┆ alpha ┆ 2_zero    ┆ 3_zero    ┆ … ┆ 597_zero  ┆ 602_zero  ┆ 605_zero  ┆ 642_zero  │
│ ---        ┆ ---   ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ i32        ┆ f64   ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 51         ┆ 18.66 ┆ -0.067979 ┆ -0.013893 ┆ … ┆ -0.14577  ┆ -0.042926 ┆ -0.016307 ┆ -0.004822 │
│ 50         ┆ 17.97 ┆ -0.067712 ┆ -0.014648 ┆ … ┆ -0.146726 ┆ -0.042897 ┆ -0.017215 ┆ -0.004549 │
│ 49         ┆ 17.28 ┆ -0.067275 ┆ -0.015436 ┆ … ┆ -0.147938 ┆ -0.042601 ┆ -0.018    ┆ -0.004014 │
│ 48         ┆ 16.26 ┆ -0.066821 ┆ -0.01668  ┆ … ┆ -0.149416 ┆ -0.042499 ┆ -0.019471 ┆ -0.003298 │
│ 47         ┆ 15.08 ┆ -0.066185 ┆ -0.018304 ┆ … ┆ -0.151241 ┆ -0.042302 ┆ -0.021392 ┆ -0.002355 │
│ …          ┆ …     ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 9          ┆ 1.0   ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 8          ┆ 2.57  ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 7          ┆ 0.84  ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 6          ┆ 0.83  ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 5          ┆ 0.98  ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
└────────────┴───────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [9]:
df_preds.write_parquet(f"{file}_preds.parquet")
df_coefs.write_parquet(f"{file}_coefs.parquet")